### ISSUE TITLE
Minimize delay on displaying local RTMP-Stream

### ISSUE THREAD

**Issue by Luk4s93** [josephnhtam/live-streaming-server-net#12]
Hi, first of all thank you for this project!

I am using it in a .NET MAUI Application on iOS, where an iPhone is not only the RTMP-Server but also the Client, showing the RTMP-Livestream on the screen. 

I want to show the stream along a view of the camera of the iPhone itself, my problem is the delay of ~2sec I get between both views. The only setting I found which could have impact was on `RtmpServerConfiguration` the setting `EnableGopCaching`. But changing it had no impact at all.

Is there any caching/delay/latency setting I've missed?

Thanks in advance!

**Comment by josephnhtam** [comment]
Hi, Luk4s93.

This library doesn’t add any intentional latency.
Setting EnableGopCaching to false can generally help, however, it might not be noticeable when the keyframe interval is low. Additionally, latency can also result from the buffering time on the receiving side.
