### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by zeropy009** [josephnhtam/live-streaming-server-net#13]
Hello! i don't know how to use it. Can you demo for a livestream video ?

**Comment by deepx** [comment]
Hi,

There is a quickstart described in the readme.md.

**Comment by zeropy009** [comment]
I read and saw that it requires a 3rd party software. Is there any way to livestream directly on websites ?

**Comment by deepx** [comment]
i believe you need a javascript-lib to embed a playerr on your website. there are a lot of good ones out there. For example: https://videojs.com/

**Comment by josephnhtam** [comment]
Hi, deepx
To display the livestream on your website, you will need to use either FLV or HLS. 
You can also refer to the source code of the admin panel, which utilizes flv.js for the HTML5 FLV Player.

**Comment by deepx** [comment]
Hi @josephnhtam.
aah, thank you. that will help @zeropy009 with his website. i personally use a streaming client like vlc or similar.

**Comment by zeropy009** [comment]
Thank you so much, now I'm starting to learn about it
