### ISSUE TITLE
Authentication Sample

### ISSUE THREAD

**Issue by vishalsmart** [josephnhtam/live-streaming-server-net#18]
Hi @josephnhtam  this is really a great work!
I want to inject some mechanism for authentication, example - 
My API server will give code to push stream, but before allowing push I want to verify the code. Can you share some sample how the inbuilt authentication can be used or customized. I could not find any sample for that on repository.

Also I am open to contribute some sample for the same if you allow, like db authentication or bearer etc, if you guide.

Vishal

**Comment by josephnhtam** [comment]
Hi @vishalsmart 
Thank you for your feedback. I have added an authorization demo.
Please feel free to create a pull request if you want to contribute.

Besides, I am planning to add unit tests for facilitating any contribution.

**Comment by vishalsmart** [comment]
@josephnhtam thanks for quick implementation!
