### ISSUE TITLE
Upload the files to Azure Blob

### ISSUE THREAD

**Issue by kasirajansfm** [josephnhtam/live-streaming-server-net#19]
First of all thanks for the wonderful project, its very useful for me.

am using this to stream my desktop and store those stream to Azure blob. Its streaming the desktop, is there any way to upload the files to azure blob.?

**Comment by josephnhtam** [comment]
Hi @kasirajansfm 
There will be a package for adding the capability to upload HLS stream to Azure blob storage, but it is not yet published.
The codes have been added in the develop branch.

**Comment by kasirajansfm** [comment]
Thanks @josephnhtam, its working for me.

**Comment by kasirajansfm** [comment]
on blob its uploaded "https://xxxx.blob.core.windows.net/livevideo/060a8774-2b72-489b-8640-8ab60c898ad4/output.m3u8" to this URL. but i need to upload its "https://xxxx.blob.core.windows.net/livevideo/demo/output.m3u8" like this, is there any possibility to change the identifier.?

**Comment by josephnhtam** [comment]
Hi @kasirajansfm 
You can implement the IHlsBlobPathResolver interface to provide a customized path.
While the path resolver object instance should be passed to HlsAzureBlobStorageConfiguration.

**Comment by kasirajansfm** [comment]
![image](https://github.com/josephnhtam/live-streaming-server-net/assets/166936661/46132722-7c97-4f27-ba11-6ca20f16b999)

how to pass TransmuxingContext here.?

**Comment by kasirajansfm** [comment]
![image](https://github.com/josephnhtam/live-streaming-server-net/assets/166936661/d82d1f52-11c1-4465-82fe-5c25b065255e)

tried like this, but its not working out.

**Comment by josephnhtam** [comment]
```
hlsUploaderConfigurator.AddAzureBlobStorage(blobContainerClient, options =>
    options.BlobPathResolver = new HlsBlobPathResolver()
);
```

This should work

**Comment by kasirajansfm** [comment]
Thanks, its worked.
