### ISSUE TITLE
HTTP-FLV not working without audio

### ISSUE THREAD

**Issue by kasirajansfm** [josephnhtam/live-streaming-server-net#20]
when i try to stream video without audio, unable to get HTTP-FLV url, its throwing 404 error.

**Comment by josephnhtam** [comment]
HI @kasirajansfm 
v0.9.0, which includes the fix, has been published to nuget.

**Comment by kasirajansfm** [comment]
Thanks for the reponse.

**Comment by kasirajansfm** [comment]
Its working fine now.
