### ISSUE TITLE
Delay on Streaming

### ISSUE THREAD

**Issue by kasirajansfm** [josephnhtam/live-streaming-server-net#22]
am facing 15sec delay when running from IIS, is there any way to reduce the delay?

**Comment by josephnhtam** [comment]
Are you using HLS?
If you use OBS studio to publish the stream, it should be better if you set keyframe interval to 1s.
Also the player-side buffer affects the delay a lot.

**Comment by kasirajansfm** [comment]
@josephnhtam 
yes am using HLS, grabbing desktop screen using ffmpeg and viewing on VLC. After made changes on ffmpeg command now its working with minimal delay. Thanks.
