### ISSUE TITLE
Excessive use of IServiceProvider

### ISSUE THREAD

**Issue by f135ta** [josephnhtam/live-streaming-server-net#24]
You have a very interesting approach to dependency injection, and coding in general. 

The IServiceProvider has tripped me up several times when trying to work with the code. The nested dependencies make it difficult to understand which classes are actually used and where.

I'd suggest removing the IServiceProvider references and actually using the dependency injection built into Net Core properly. It will make the code easier to use, easier to test and easier to understand.

[Microsoft recommendation for not using IServiceProvider](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.2#recommendations)

**Comment by josephnhtam** [comment]
Hi @f135ta 

Thank you for your suggestion. I assume you are referring to the event dispatcher classes that use the observer or mediator pattern.
In my opinion, it is not uncommon to inject the IoC container, the IServiceProvider, to dynamically obtain references to the required handlers. Moreover, this approach helps avoid circular references by eliminating the need for direct dependencies. 
However, any pull requests or discussions are welcome.

**Comment by josephnhtam** [comment]
Unit tests have been added
[RtmpMessageDispatcher.Test.cs](https://github.com/josephnhtam/live-streaming-server-net/blob/develop/test/LiveStreamingServerNet.Rtmp.Test/RtmpEventHandlers/Dispatcher/RtmpMessageDispatcher.Test.cs)
[RtmpCommandDispatcher.Test.cs](https://github.com/josephnhtam/live-streaming-server-net/blob/develop/test/LiveStreamingServerNet.Rtmp.Test/RtmpEventHandlers/Commands/Dispatcher/RtmpCommandDispatcher.Test.cs)
