### ISSUE TITLE
Can not preview on Safari

### ISSUE THREAD

**Issue by yuessir** [josephnhtam/live-streaming-server-net#25]
The preview feature can not work on IOS'(16.7) safari browser.

**Comment by josephnhtam** [comment]
The admin panel UI uses flv.js for the flv player, which unfortunately doesn't support iOS.

**Comment by yuessir** [comment]
Can you integrate HLS streaming into the project？ If it’s iOS, the UI's logic will switch to HLS (HTTP Live Streaming).

**Comment by josephnhtam** [comment]
For HLS, you can find the docs [here](https://josephnhtam.github.io/live-streaming-server-net/docs/essentials/serving-hls.html).
I will consider adding HLS to admin panel as well.

**Comment by josephnhtam** [comment]
Hi @yuessir 
Sorry for the delay.
HLS preview has been added to admin panel ui in v0.21.0.

**Comment by 0x55xx5** [comment]
> Hi @yuessir
> Sorry for the delay.
> HLS preview has been added to admin panel ui in v0.21.0.
> Please refer to the [LiveStreamingServerNet.StandaloneDemo](https://github.com/josephnhtam/live-streaming-server-net/blob/develop/samples/LiveStreamingServerNet.StandaloneDemo/Program.cs)

i’ll try it, thanks for the commit.

**Comment by yuessir** [comment]
I will try it, thanks for the awesome commit.
