### ISSUE TITLE
User password authentication

### ISSUE THREAD

**Issue by kirikoglu** [josephnhtam/live-streaming-server-net#35]
Hi,

Can you implement RTMP source authentication by using user password?

**Comment by josephnhtam** [comment]
Hi @kirikoglu 
You can implement your authorization handler to check the username and password.
Please refer to [](https://github.com/josephnhtam/live-streaming-server-net/blob/develop/samples/LiveStreamingServerNet.AuthorizationDemo/Program.cs)
