### ISSUE TITLE
Multi-Bitrate HLS

### ISSUE THREAD

**Issue by chriskooken** [josephnhtam/live-streaming-server-net#37]
This project looks awesome. I am transitioning away from Azure Media services and this could be a good fit. Does the HLS transmuxer support multi-bitrate streams or is it just a single bitrate. If multiple, is there a place to control the quality levels that are served?

**Comment by josephnhtam** [comment]
Adaptive HLS transcoding has been added in v0.12.0
Please refer to [LiveStreamingServerNet.AdaptiveHlsDemo](https://github.com/josephnhtam/live-streaming-server-net/tree/develop/samples/LiveStreamingServerNet.AdaptiveHlsDemo)
