### ISSUE TITLE
Is there any consideration for H265 support?

### ISSUE THREAD

**Issue by wosledon** [josephnhtam/live-streaming-server-net#41]

**Comment by josephnhtam** [comment]
Hi @wosledon 
This library is designed to support h265 as well, however I haven't tested it yet.

**Comment by wosledon** [comment]
> Hi @wosledon This library is designed to support h265 as well, however I haven't tested it yet.

Thanks for your support! For my tests, H265 works wrong.

**Comment by josephnhtam** [comment]
Thanks for reporting. I will check it when I have time.

**Comment by josephnhtam** [comment]
HEVC/H.265 support has been added in v0.16.0

**Comment by wosledon** [comment]
> HEVC/H.265 support has been added in [v0.16.0](https://www.nuget.org/packages/LiveStreamingServerNet/0.16.0)

Thanks for your support!
