### ISSUE TITLE
Streaming from own code

### ISSUE THREAD

**Issue by caveofjulian** [josephnhtam/live-streaming-server-net#43]
First of all, this is a really dope project. Thank you for your contribution!

I have a couple of questions, maybe I don't understand well and I think it is still a bit early for proper documentation (which btw is not a jab). Some of the code samples go over my head, perhaps also because I don't know all terminology. I want to have a live streaming server, which this seems to fully offer with a million options - so that is fantastic. My usecase is for streaming drone footage (multiple drones at once) to the server and a frontend where users can see the streams. However, I don't understand how to stream to the server from e.g. another project rather than OBS or something like that. Do you by any chance have a sample for this? Also would my usecase, altho I appreciate the auth and all, be maybe too simplistic and would this add a lot of overhead to the streaming?  Or would I even be better off simply using .NET Web API endpoints or simplistic TCP/UDP server splitting the streams up in chunks myself?

**Comment by josephnhtam** [comment]
Hi @caveofjulian 
My knowledge of drones is quite limited. 
This library facilitates the creation of a media server with RTMP ingestion capability. 
While RTMP is a widely-used transmission protocol employed by many social media platforms such as Twitch.tv, Facebook, and YouTube. 
If your drone can stream the camera feed to these social media platforms via RTMP, it should also be capable of streaming to the live streaming server created with this library as well.
So you may need to check if your drone supports RTMP streaming.

**Comment by caveofjulian** [comment]
Hi, thanks for your reply. I'm making my own drones so this is no problem and RTMP is widely used in drones.

Thanks for your reply, I think it is worth actually delving into the project as it looks very promising. Thank you!
