### ISSUE TITLE
How do I manage client connections?

### ISSUE THREAD

**Issue by wosledon** [josephnhtam/live-streaming-server-net#50]
The scenario is like this, I need to automatically stop the RTMP stream when there is no client watching, but I can't seem to get the full RTMP connection information and client information

**Comment by josephnhtam** [comment]
Hi @wosledon 

I have released v0.14.2, which exposes IRtmpStreamManager to facilitate a similar use case.

Before v0.14.2, you may have needed to implement IRtmpServerStreamEventHandler to listen for the publishing and subscribing events in order to know which clients were publishing and subscribing to streams. Now, you can use IRtmpStreamManager to get this information.

I have also updated the LiveStreamingServerNet.EventsDemo to show the usage of IRtmpStreamManager.

**Comment by wosledon** [comment]
okey, thanks!

**Comment by wosledon** [comment]
> Hi @wosledon
> 
> I have released v0.14.2, which exposes IRtmpStreamManager to facilitate a similar use case.
> 
> Before v0.14.2, you may need to implement IRtmpServerStreamEventHandler to listen for the publishing and subscribing events in order to know which clients were publishing and subscribing to streams. Now, you can use IRtmpStreamManager to get this information.
> 
> I have also updated the LiveStreamingServerNet.EventsDemo to show the usage of IRtmpStreamManager.

Hey, for my testing, I couldn't get if the player was connected to the server.

**Comment by josephnhtam** [comment]
Can IRtmpStream.Subsribers help?

**Comment by wosledon** [comment]
> Can IRtmpStream.Subsribers help?

I connected using the VLC player and the `Subsribers` is not receiving the connection event

**Comment by josephnhtam** [comment]
The Subscribers list will not get updated in realtime.
Please refer to [RTMP Server Events](https://josephnhtam.github.io/live-streaming-server-net/tutorials/rtmp-server-events/) in order to listen the `OnRtmpStreamSubscribedAsync` event, and call IStreamManager.GetStream again.

**Comment by josephnhtam** [comment]
I have tested with the following code, which works for me
```
using LiveStreamingServerNet;
using LiveStreamingServerNet.Rtmp.Contracts;
using LiveStreamingServerNet.Utilities.Contracts;
using System.Net;

var liveStreamingServer = LiveStreamingServerBuilder.Create()
    .ConfigureRtmpServer(options =>
        options.AddStreamEventHandler<RtmpMediaServerStreamService>())
    .Build();

await liveStreamingServer.RunAsync(new IPEndPoint(IPAddress.Any, 1935));

public class RtmpMediaServerStreamService : IRtmpServerStreamEventHandler
{
    public ValueTask OnRtmpStreamMetaDataReceivedAsync(IEventContext context, uint clientId, string streamPath, IReadOnlyDictionary<string, object> metaData)
    {
        Console.WriteLine($"A-{clientId}, {streamPath}");

        return ValueTask.CompletedTask;
    }

    public ValueTask OnRtmpStreamPublishedAsync(IEventContext context, uint clientId, string streamPath, IReadOnlyDictionary<string, string> streamArguments)
    {
        Console.WriteLine($"B-{clientId}, {streamPath}");
        return ValueTask.CompletedTask;
    }

    public ValueTask OnRtmpStreamSubscribedAsync(IEventContext context, uint clientId, string streamPath, IReadOnlyDictionary<string, string> streamArguments)
    {
        Console.WriteLine($"C-{clientId}, {streamPath}");
        return ValueTask.CompletedTask;
    }

    public ValueTask OnRtmpStreamUnpublishedAsync(IEventContext context, uint clientId, string streamPath)
    {
        Console.WriteLine($"D-{clientId}, {streamPath}");
        return ValueTask.CompletedTask;
    }

    public ValueTask OnRtmpStreamUnsubscribedAsync(IEventContext context, uint clientId, string streamPath)
    {
        Console.WriteLine($"E-{clientId}, {streamPath}");
        return ValueTask.CompletedTask;
    }
}
```

OnRtmpStreamSubscribedAsync is invoked when a watcher subscribe the stream, and OnRtmpStreamUnsubscribedAsync is invoked when the watch leaves.
