### ISSUE TITLE
Persisting the outdated .ts segments index in the m3u8 file for HLS streams

### ISSUE THREAD

**Issue by shreyanshJain852** [josephnhtam/live-streaming-server-net#62]
@josephnhtam, Is there a way to persist the .ts segments in the m3u8 which are outdated?

I found a `DeleteOutdatedSegments` which was used for restricting deletion of older segments in an ongoing stream, to maintain all the streamed ts segments.
But the m3u8 file is getting updated to the latest segments on each write operation. Would it be possible to maintain the older ts segments as well in the m3u8 file?

**Comment by josephnhtam** [comment]
Hi @shreyanshJain852 
You can set the SegmentListSize in HlsTransmuxerConfiguration to int.MaxValue for achieving this
