### ISSUE TITLE
How to understand the project

### ISSUE THREAD

**Issue by aleevan2812** [josephnhtam/live-streaming-server-net#64]
I am researching about vms (video media services), so where should i start to understand this project. 
Sorry for this ambiguity
Thks for reading.

**Comment by josephnhtam** [comment]
Hi @aleevan2812 
You can follow the [Quick Start](https://github.com/josephnhtam/live-streaming-server-net?tab=readme-ov-file#quick-start) to set up an RTMP server.
With an RTMP server, you can use software like OBS Studio to publish a video stream to it and play the video stream with software like VLC player.
Besides, you can check the [Documentation](https://josephnhtam.github.io/live-streaming-server-net/) to look at the additional features like serving the video stream via FLV or HLS, which allow you to play the video in a browser.

**Comment by aleevan2812** [comment]
I mean how to understand how this project work, some basic knowlage, ...

**Comment by josephnhtam** [comment]
I am not sure if I understand your question correctly.
If you want to know how RTMP works, perhaps [Adobe RTMP Specification](https://rtmp.veriskope.com/docs/spec/) can help you.
