### ISSUE TITLE
Add max-muxing-size for Adaptive HLS Streaming

### ISSUE THREAD

**Issue by kirikoglu** [josephnhtam/live-streaming-server-net#75]
Hi,

FFmpeg fails on Windows while running Adaptive HLS demo.

"-max_muxing_queue_size 1024" param solving this.

**Comment by josephnhtam** [comment]
Hi @kirikoglu 

You can try to add the below to add the "-max_muxing_queue_size 1024" param for now.
```
options.PerformanceOptions = options.PerformanceOptions with
{
    ExtraArguments = "-max_muxing_queue_size 1024"
};
```

Btw, I will try to improve adaptive HLS transcoder to make it more flexible.

**Comment by kirikoglu** [comment]
Yes, thanks

**Comment by josephnhtam** [comment]
`PerformanceOptions` now contains `MaxMuxingQueueSize`, which is 1024 by default.
